### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-quickstart#10]
since our setuptools is running problems, do we need a MANIFEST.in that would include requirements.txt and probably README & License?

**Comment by sils1297** [comment]
this is the one from coala, it works pretty fine, guess we won't need the
docs though:

include README.md
include LICENSE
include test-requirements.txt
include requirements.txt
include setup.cfg
recursive-include docs *



Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-05 18:31 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Comment by Adrianzatreanu** [comment]
yes, at the coala one i was looking. so i should add it?

**Comment by Adrianzatreanu** [comment]
we also dont have a setup.cfg / test-reqs yet, so theres no point in including them yet :)

**Comment by sils1297** [comment]
:+1:

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-05 18:33 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com
