### ISSUE TITLE
Don't ask user about bears

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-quickstart#19]
It'd be better to ask user to confirm detected languages, then generate the config completely with  comments.

That's way easier for him to follow.

**Comment by hypothesist** [comment]
For the example I used, there were about 13-14 bears. Use all of them?

**Comment by sils1297** [comment]
we should try taking a meaningful selection of bears organized in sections so they don't conflict IMO

**Comment by hypothesist** [comment]
I'm thinking of generating the sections ourselves since we have the language information. A section for each language and the corresponding bears for each language in that section. We can also fill the files field ourselves for each section.

**Comment by sils1297** [comment]
this is done isn't it?

**Comment by hypothesist** [comment]
yeah
