### ISSUE TITLE
My email needs update in setup.py

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-quickstart#31]
The email specified there is no longer available. Needs to be replaced with ``adrianzatreanu1@gmail.com`` at the maintainers_emails in setup.py

**Comment by GuessWhoSamFoo** [comment]
May I be assigned to this one? It will be my first commit for this project!

**Comment by sils1297** [comment]
Yes, totally - seeing forward to it :) CC @hypothesist will you be around for review?

**Comment by sils1297** [comment]
@GuessWhoSamFoo you might need ping us on gitter about review, I'm not sure if our bot is correctly set up on this repository.

**Comment by hypothesist** [comment]
@sils1297 sorry still in exam mode for another week or so :(

glad to welcome @GuessWhoSamFoo to the coala community though :)
